<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use App\Models\AiModel;
use Illuminate\Support\Facades\DB;

class AiModelsSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        // Clear existing models (SQLite compatible)
        DB::table('ai_models')->delete();

        $models = [
            // OpenAI Models
            [
                'name' => 'GPT-4o',
                'provider' => 'openai',
                'model_identifier' => 'gpt-4o',
                'api_url' => 'https://api.openai.com/v1/chat/completions',
                'description' => 'Most advanced OpenAI model with vision support',
                'icon' => '/images/ai-models/ChatGPT.png',
                'color' => '#10a37f',
                'is_active' => true,
                'supports_vision' => true,
                'max_tokens' => 4096,
                'temperature' => 0.7,
                'order' => 1,
            ],
            [
                'name' => 'GPT-4o Mini',
                'provider' => 'openai',
                'model_identifier' => 'gpt-4o-mini',
                'api_url' => 'https://api.openai.com/v1/chat/completions',
                'description' => 'Faster and more efficient GPT-4o variant',
                'icon' => '/images/ai-models/ChatGPT.png',
                'color' => '#10a37f',
                'is_active' => true,
                'supports_vision' => true,
                'max_tokens' => 4096,
                'temperature' => 0.7,
                'order' => 2,
            ],
            [
                'name' => 'GPT-4 Turbo',
                'provider' => 'openai',
                'model_identifier' => 'gpt-4-turbo-preview',
                'api_url' => 'https://api.openai.com/v1/chat/completions',
                'description' => 'Fast and powerful GPT-4 model',
                'icon' => '/images/ai-models/ChatGPT.png',
                'color' => '#10a37f',
                'is_active' => true,
                'supports_vision' => false,
                'max_tokens' => 4096,
                'temperature' => 0.7,
                'order' => 3,
            ],
            [
                'name' => 'GPT-4',
                'provider' => 'openai',
                'model_identifier' => 'gpt-4',
                'api_url' => 'https://api.openai.com/v1/chat/completions',
                'description' => 'Standard GPT-4 model for complex tasks',
                'icon' => '/images/ai-models/ChatGPT.png',
                'color' => '#10a37f',
                'is_active' => true,
                'supports_vision' => false,
                'max_tokens' => 8192,
                'temperature' => 0.7,
                'order' => 4,
            ],
            [
                'name' => 'GPT-3.5 Turbo',
                'provider' => 'openai',
                'model_identifier' => 'gpt-3.5-turbo',
                'api_url' => 'https://api.openai.com/v1/chat/completions',
                'description' => 'Fast and efficient for everyday tasks',
                'icon' => '/images/ai-models/ChatGPT.png',
                'color' => '#10a37f',
                'is_active' => true,
                'supports_vision' => false,
                'max_tokens' => 4096,
                'temperature' => 0.7,
                'order' => 5,
            ],

            // Anthropic (Claude) Models
            [
                'name' => 'Claude 3 Opus',
                'provider' => 'anthropic',
                'model_identifier' => 'claude-3-opus-20240229',
                'api_url' => 'https://api.anthropic.com/v1/messages',
                'description' => 'Most powerful Claude model for complex tasks',
                'icon' => '/images/ai-models/Claude.png',
                'color' => '#D97757',
                'is_active' => true,
                'supports_vision' => true,
                'max_tokens' => 4096,
                'temperature' => 0.7,
                'order' => 5,
            ],
            [
                'name' => 'Claude 3 Sonnet',
                'provider' => 'anthropic',
                'model_identifier' => 'claude-3-sonnet-20240229',
                'api_url' => 'https://api.anthropic.com/v1/messages',
                'description' => 'Balanced performance and speed',
                'icon' => '/images/ai-models/Claude.png',
                'color' => '#D97757',
                'is_active' => true,
                'supports_vision' => true,
                'max_tokens' => 4096,
                'temperature' => 0.7,
                'order' => 6,
            ],
            [
                'name' => 'Claude 3 Haiku',
                'provider' => 'anthropic',
                'model_identifier' => 'claude-3-haiku-20240307',
                'api_url' => 'https://api.anthropic.com/v1/messages',
                'description' => 'Fastest Claude model for quick responses',
                'icon' => '/images/ai-models/Claude.png',
                'color' => '#D97757',
                'is_active' => true,
                'supports_vision' => true,
                'max_tokens' => 4096,
                'temperature' => 0.7,
                'order' => 7,
            ],
            [
                'name' => 'Claude 3.5 Sonnet',
                'provider' => 'anthropic',
                'model_identifier' => 'claude-3-5-sonnet-20241022',
                'api_url' => 'https://api.anthropic.com/v1/messages',
                'description' => 'Latest improved Sonnet model',
                'icon' => '/images/ai-models/Claude.png',
                'color' => '#D97757',
                'is_active' => true,
                'supports_vision' => true,
                'max_tokens' => 8192,
                'temperature' => 0.7,
                'order' => 8,
            ],

            // Google Gemini Models - Latest 2.0 Series
            [
                'name' => 'Gemini 2.0 Flash',
                'provider' => 'google',
                'model_identifier' => 'gemini-2.0-flash',
                'api_url' => 'https://generativelanguage.googleapis.com/v1beta/models/gemini-2.0-flash:generateContent',
                'description' => 'Latest Gemini 2.0 Flash - Fast, powerful, and recommended for most tasks',
                'icon' => '/images/ai-models/gemini.png',
                'color' => '#4285F4',
                'is_active' => true,
                'supports_vision' => true,
                'max_tokens' => 8192,
                'temperature' => 0.7,
                'order' => 9,
            ],
            [
                'name' => 'Gemini 2.0 Flash-Lite',
                'provider' => 'google',
                'model_identifier' => 'gemini-2.0-flash-lite',
                'api_url' => 'https://generativelanguage.googleapis.com/v1beta/models/gemini-2.0-flash-lite:generateContent',
                'description' => 'Fastest and cheapest Gemini 2.0 model - Great for simple tasks',
                'icon' => '/images/ai-models/gemini.png',
                'color' => '#34A853',
                'is_active' => true,
                'supports_vision' => true,
                'max_tokens' => 8192,
                'temperature' => 0.7,
                'order' => 10,
            ],
            [
                'name' => 'Gemini 2.0 Flash Experimental',
                'provider' => 'google',
                'model_identifier' => 'gemini-2.0-flash-exp',
                'api_url' => 'https://generativelanguage.googleapis.com/v1beta/models/gemini-2.0-flash-exp:generateContent',
                'description' => 'Experimental Gemini 2.0 Flash with cutting-edge features',
                'icon' => '/images/ai-models/gemini.png',
                'color' => '#EA4335',
                'is_active' => false,
                'supports_vision' => true,
                'max_tokens' => 8192,
                'temperature' => 0.7,
                'order' => 11,
            ],
            [
                'name' => 'Gemini 2.0 Flash Thinking',
                'provider' => 'google',
                'model_identifier' => 'gemini-2.0-flash-thinking-exp',
                'api_url' => 'https://generativelanguage.googleapis.com/v1beta/models/gemini-2.0-flash-thinking-exp:generateContent',
                'description' => 'Gemini 2.0 with enhanced reasoning and thinking capabilities',
                'icon' => '/images/ai-models/gemini.png',
                'color' => '#FBBC04',
                'is_active' => false,
                'supports_vision' => true,
                'max_tokens' => 8192,
                'temperature' => 0.7,
                'order' => 12,
            ],

            // Google Gemini Models - 1.5 Series
            [
                'name' => 'Gemini 1.5 Pro',
                'provider' => 'google',
                'model_identifier' => 'gemini-1.5-pro',
                'api_url' => 'https://generativelanguage.googleapis.com/v1beta/models/gemini-1.5-pro:generateContent',
                'description' => 'Most capable Gemini 1.5 model for complex reasoning tasks',
                'icon' => '/images/ai-models/gemini.png',
                'color' => '#4285F4',
                'is_active' => false,
                'supports_vision' => true,
                'max_tokens' => 8192,
                'temperature' => 0.7,
                'order' => 13,
            ],
            [
                'name' => 'Gemini 1.5 Pro Latest',
                'provider' => 'google',
                'model_identifier' => 'gemini-1.5-pro-latest',
                'api_url' => 'https://generativelanguage.googleapis.com/v1beta/models/gemini-1.5-pro-latest:generateContent',
                'description' => 'Latest stable Gemini 1.5 Pro with newest improvements',
                'icon' => '/images/ai-models/gemini.png',
                'color' => '#4285F4',
                'is_active' => false,
                'supports_vision' => true,
                'max_tokens' => 8192,
                'temperature' => 0.7,
                'order' => 14,
            ],
            [
                'name' => 'Gemini 1.5 Flash',
                'provider' => 'google',
                'model_identifier' => 'gemini-1.5-flash',
                'api_url' => 'https://generativelanguage.googleapis.com/v1beta/models/gemini-1.5-flash:generateContent',
                'description' => 'Fast and efficient Gemini 1.5 model for everyday tasks',
                'icon' => '/images/ai-models/gemini.png',
                'color' => '#34A853',
                'is_active' => false,
                'supports_vision' => true,
                'max_tokens' => 8192,
                'temperature' => 0.7,
                'order' => 15,
            ],
            [
                'name' => 'Gemini 1.5 Flash Latest',
                'provider' => 'google',
                'model_identifier' => 'gemini-1.5-flash-latest',
                'api_url' => 'https://generativelanguage.googleapis.com/v1beta/models/gemini-1.5-flash-latest:generateContent',
                'description' => 'Latest stable Gemini 1.5 Flash with newest improvements',
                'icon' => '/images/ai-models/gemini.png',
                'color' => '#34A853',
                'is_active' => false,
                'supports_vision' => true,
                'max_tokens' => 8192,
                'temperature' => 0.7,
                'order' => 16,
            ],
            [
                'name' => 'Gemini 1.5 Flash-8B',
                'provider' => 'google',
                'model_identifier' => 'gemini-1.5-flash-8b',
                'api_url' => 'https://generativelanguage.googleapis.com/v1beta/models/gemini-1.5-flash-8b:generateContent',
                'description' => 'Smaller, faster Gemini Flash variant for quick responses',
                'icon' => '/images/ai-models/gemini.png',
                'color' => '#34A853',
                'is_active' => false,
                'supports_vision' => true,
                'max_tokens' => 8192,
                'temperature' => 0.7,
                'order' => 17,
            ],

            // Google Gemini Nano - Lightweight model
            [
                'name' => 'Gemini Nano',
                'provider' => 'google',
                'model_identifier' => 'gemini-nano',
                'api_url' => 'https://generativelanguage.googleapis.com/v1beta/models/gemini-nano:generateContent',
                'description' => 'Ultra-lightweight on-device model for quick responses',
                'icon' => '/images/ai-models/gemini.png',
                'color' => '#34A853',
                'is_active' => false,
                'supports_vision' => false,
                'max_tokens' => 1024,
                'temperature' => 0.7,
                'order' => 18,
            ],

            // DeepSeek Models
            [
                'name' => 'DeepSeek Chat',
                'provider' => 'deepseek',
                'model_identifier' => 'deepseek-chat',
                'api_url' => 'https://api.deepseek.com/v1/chat/completions',
                'description' => 'Advanced reasoning and coding model',
                'icon' => '/images/ai-models/DeepSeek.png',
                'color' => '#6366f1',
                'is_active' => true,
                'supports_vision' => false,
                'max_tokens' => 4096,
                'temperature' => 0.7,
                'order' => 16,
            ],
            [
                'name' => 'DeepSeek Coder',
                'provider' => 'deepseek',
                'model_identifier' => 'deepseek-coder',
                'api_url' => 'https://api.deepseek.com/v1/chat/completions',
                'description' => 'Specialized for coding tasks',
                'icon' => '/images/ai-models/DeepSeek.png',
                'color' => '#6366f1',
                'is_active' => true,
                'supports_vision' => false,
                'max_tokens' => 4096,
                'temperature' => 0.7,
                'order' => 17,
            ],
        ];

        foreach ($models as $model) {
            AiModel::create($model);
        }

        $this->command->info('✅ AI Models seeded successfully with API URLs!');
    }
}
