<?php

namespace Database\Seeders;

use App\Models\UserPlan;
use Illuminate\Database\Seeder;

class UserPlanSeeder extends Seeder
{
    /**
     * Final pricing plans:
     * AI Models: Gemini Flash (default) + GPT-4o Mini (paid plans)
     * Chat: Limited in Free, Unlimited in all paid
     * Whiteboard: NEVER unlimited (₹3-5/video server cost)
     */
    public function run(): void
    {
        $plans = [
            // ── FREE – ₹0/month ──
            [
                'name' => 'Free',
                'slug' => 'free',
                'description' => 'Start Your Learning Journey',
                'price' => 0,
                'billing_period' => 'month',
                'billing_description' => 'Free Forever',
                'validity_days' => 30,
                'message_tokens' => 0,
                'image_credits' => 0,
                'api_calls' => 0,
                'image_uploads' => 0,
                'can_use_gpt4' => false,
                'can_use_claude' => false,
                'can_use_deepseek' => false,
                'can_use_grok' => false,
                'unlimited_credits' => false,
                'is_active' => true,
                'order' => 1,
                'features' => json_encode([
                    'popular' => false,
                    'recommended' => false,
                    'daily_limits' => [
                        'chat_messages_per_day' => 10,
                        'video_quiz_per_day' => 2,
                        'whiteboard_videos_per_month' => 2,
                        'topic_quiz_per_day' => 3,
                        'exam_prep_per_day' => 1,
                        'scan_solve_per_day' => 3,
                        'pdf_uploads_per_month' => 1,
                    ],
                    'max_video_length_seconds' => 30,
                    'frames_per_video' => 5,
                    'pages_per_pdf' => 5,
                    'history_days' => 3,
                    'watermark' => true,
                    'ads' => true,
                    'priority_queue' => false,
                    'video_quality' => 'sd',
                    'device_limit' => 1,
                    'analytics_tier' => 'basic',
                    'features_list' => [
                        '10 AI Chat Messages / Day',
                        '2 Video Quizzes / Day',
                        '2 Whiteboard Videos / Month',
                        '3 Topic Quizzes / Day',
                        '1 Exam Prep / Day',
                        '3 Scan & Solve / Day',
                        '1 PDF Upload / Month (5 pages)',
                        '3 Days History',
                        'Gemini Flash AI',
                        'Watermark on Videos',
                        'Ad-Supported',
                    ],
                ]),
            ],

            // ── STARTER – ₹79/month ──
            [
                'name' => 'Starter',
                'slug' => 'starter',
                'description' => 'Boost Your Exam Prep',
                'price' => 79,
                'billing_period' => 'month',
                'billing_description' => '₹79 / month',
                'validity_days' => 30,
                'message_tokens' => 0,
                'image_credits' => 0,
                'api_calls' => 0,
                'image_uploads' => 0,
                'can_use_gpt4' => true,
                'can_use_claude' => false,
                'can_use_deepseek' => false,
                'can_use_grok' => false,
                'unlimited_credits' => false,
                'is_active' => true,
                'order' => 2,
                'features' => json_encode([
                    'popular' => false,
                    'recommended' => false,
                    'daily_limits' => [
                        'chat_messages_per_day' => -1,
                        'video_quiz_per_day' => 5,
                        'whiteboard_videos_per_month' => 5,
                        'topic_quiz_per_day' => 10,
                        'exam_prep_per_day' => 3,
                        'scan_solve_per_day' => 10,
                        'pdf_uploads_per_month' => 5,
                    ],
                    'max_video_length_seconds' => 60,
                    'frames_per_video' => 8,
                    'pages_per_pdf' => 15,
                    'history_days' => 7,
                    'watermark' => false,
                    'ads' => false,
                    'priority_queue' => false,
                    'video_quality' => 'sd',
                    'device_limit' => 2,
                    'analytics_tier' => 'basic',
                    'features_list' => [
                        'Unlimited AI Chat',
                        'Gemini Flash + GPT-4o Mini',
                        '5 Video Quizzes / Day',
                        '5 Whiteboard Videos / Month',
                        '10 Topic Quizzes / Day',
                        '3 Exam Prep / Day',
                        '10 Scan & Solve / Day',
                        '5 PDF Uploads / Month (15 pages)',
                        '7 Days History',
                        'No Watermark',
                        'Ad-Free Experience',
                    ],
                ]),
            ],

            // ── PRO – ₹249/month ⭐ MOST POPULAR ──
            [
                'name' => 'Pro',
                'slug' => 'pro',
                'description' => 'The Topper\'s Secret Weapon',
                'price' => 249,
                'billing_period' => 'month',
                'billing_description' => '₹249 / month',
                'validity_days' => 30,
                'message_tokens' => 0,
                'image_credits' => 0,
                'api_calls' => 0,
                'image_uploads' => 0,
                'can_use_gpt4' => true,
                'can_use_claude' => false,
                'can_use_deepseek' => false,
                'can_use_grok' => false,
                'unlimited_credits' => false,
                'is_active' => true,
                'order' => 3,
                'features' => json_encode([
                    'popular' => true,
                    'recommended' => true,
                    'daily_limits' => [
                        'chat_messages_per_day' => -1,
                        'video_quiz_per_day' => 15,
                        'whiteboard_videos_per_month' => 15,
                        'topic_quiz_per_day' => -1,
                        'exam_prep_per_day' => -1,
                        'scan_solve_per_day' => 30,
                        'pdf_uploads_per_month' => 20,
                    ],
                    'max_video_length_seconds' => 180,
                    'frames_per_video' => 15,
                    'pages_per_pdf' => 30,
                    'history_days' => 30,
                    'watermark' => false,
                    'ads' => false,
                    'priority_queue' => true,
                    'video_quality' => 'hd',
                    'device_limit' => 3,
                    'analytics_tier' => 'standard',
                    'features_list' => [
                        'Unlimited AI Chat',
                        'Gemini Flash + GPT-4o Mini',
                        '15 Video Quizzes / Day',
                        '15 Whiteboard Videos / Month',
                        'Unlimited Topic Quizzes',
                        'Unlimited Exam Prep',
                        '30 Scan & Solve / Day',
                        '20 PDF Uploads / Month (30 pages)',
                        '30 Days History',
                        'Priority Processing',
                        'HD Video Quality',
                        'No Watermark',
                        'Ad-Free Experience',
                    ],
                ]),
            ],

            // ── ULTIMATE – ₹599/month ──
            [
                'name' => 'Ultimate',
                'slug' => 'ultimate',
                'description' => 'Maximum Power for Serious Students',
                'price' => 599,
                'billing_period' => 'month',
                'billing_description' => '₹599 / month',
                'validity_days' => 30,
                'message_tokens' => 0,
                'image_credits' => 0,
                'api_calls' => 0,
                'image_uploads' => 0,
                'can_use_gpt4' => true,
                'can_use_claude' => false,
                'can_use_deepseek' => false,
                'can_use_grok' => false,
                'unlimited_credits' => false,
                'is_active' => true,
                'order' => 4,
                'features' => json_encode([
                    'popular' => false,
                    'recommended' => false,
                    'daily_limits' => [
                        'chat_messages_per_day' => -1,
                        'video_quiz_per_day' => -1,
                        'whiteboard_videos_per_month' => 30,
                        'topic_quiz_per_day' => -1,
                        'exam_prep_per_day' => -1,
                        'scan_solve_per_day' => 100,
                        'pdf_uploads_per_month' => 50,
                    ],
                    'max_video_length_seconds' => 600,
                    'frames_per_video' => 40,
                    'pages_per_pdf' => 50,
                    'history_days' => -1,
                    'watermark' => false,
                    'ads' => false,
                    'priority_queue' => true,
                    'video_quality' => 'hd',
                    'device_limit' => 5,
                    'analytics_tier' => 'advanced',
                    'features_list' => [
                        'Unlimited AI Chat',
                        'Gemini Flash + GPT-4o Mini',
                        'Unlimited Video Quizzes',
                        '30 Whiteboard Videos / Month',
                        'Unlimited Topic Quizzes',
                        'Unlimited Exam Prep',
                        '100 Scan & Solve / Day',
                        '50 PDF Uploads / Month (50 pages)',
                        'Unlimited History',
                        'Priority Processing',
                        'HD Video Quality',
                        'Up to 5 Devices',
                        'Advanced Analytics',
                        'No Watermark',
                        'Ad-Free Experience',
                    ],
                ]),
            ],

            // ── LIFETIME – ₹4,999/year (one-time) ──
            [
                'name' => 'Lifetime',
                'slug' => 'lifetime',
                'description' => '1 Year of Unlimited Learning - Best Value',
                'price' => 4999,
                'billing_period' => 'year',
                'billing_description' => '₹4,999 / year (Save 30%)',
                'validity_days' => 365,
                'message_tokens' => 0,
                'image_credits' => 0,
                'api_calls' => 0,
                'image_uploads' => 0,
                'can_use_gpt4' => true,
                'can_use_claude' => false,
                'can_use_deepseek' => false,
                'can_use_grok' => false,
                'unlimited_credits' => false,
                'is_active' => true,
                'order' => 5,
                'features' => json_encode([
                    'popular' => false,
                    'recommended' => false,
                    'daily_limits' => [
                        'chat_messages_per_day' => -1,
                        'video_quiz_per_day' => -1,
                        'whiteboard_videos_per_month' => 30,
                        'topic_quiz_per_day' => -1,
                        'exam_prep_per_day' => -1,
                        'scan_solve_per_day' => 100,
                        'pdf_uploads_per_month' => 50,
                    ],
                    'max_video_length_seconds' => 600,
                    'frames_per_video' => 40,
                    'pages_per_pdf' => 50,
                    'history_days' => -1,
                    'watermark' => false,
                    'ads' => false,
                    'priority_queue' => true,
                    'video_quality' => 'hd',
                    'device_limit' => 5,
                    'analytics_tier' => 'advanced',
                    'features_list' => [
                        'Everything in Ultimate',
                        'Unlimited AI Chat',
                        'Gemini Flash + GPT-4o Mini',
                        'Unlimited Video Quizzes',
                        '30 Whiteboard Videos / Month',
                        'Unlimited Topic Quizzes',
                        'Unlimited Exam Prep',
                        '100 Scan & Solve / Day',
                        '50 PDF Uploads / Month (50 pages)',
                        'Unlimited History',
                        'Priority Processing',
                        'HD Video Quality',
                        'Up to 5 Devices',
                        'Advanced Analytics',
                        'No Watermark',
                        'Ad-Free Experience',
                        'Save 30% vs Monthly',
                    ],
                ]),
            ],
        ];

        // Remove old plans not in new structure
        UserPlan::whereNotIn('slug', ['free', 'starter', 'pro', 'ultimate', 'lifetime'])->delete();

        foreach ($plans as $plan) {
            UserPlan::updateOrCreate(
                ['slug' => $plan['slug']],
                $plan
            );
        }
    }
}
